name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天00:00运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0  # 获取所有历史

      - name: Configure Git
        run: |
          git config user.name "JackieIris"
          git config user.email "liurain0312@gmail.com"

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/Licoy/ChatGPT-Midjourney.git
          git fetch upstream
          git merge upstream/master
          git push origin master
